export interface Country {
  value: string;
  label: string;
  labelAr?: string;
}

export const COUNTRIES: Country[] = [
  { value: "AF", label: "Afghanistan", labelAr: "أفغانستان" },
  { value: "AL", label: "Albania", labelAr: "ألبانيا" },
  { value: "DZ", label: "Algeria", labelAr: "الجزائر" },
  { value: "AD", label: "Andorra", labelAr: "أندورا" },
  { value: "AO", label: "Angola", labelAr: "أنغولا" },
  { value: "AG", label: "Antigua and Barbuda", labelAr: "أنتيغوا وباربودا" },
  { value: "AR", label: "Argentina", labelAr: "الأرجنتين" },
  { value: "AM", label: "Armenia", labelAr: "أرمينيا" },
  { value: "AU", label: "Australia", labelAr: "أستراليا" },
  { value: "AT", label: "Austria", labelAr: "النمسا" },
  { value: "AZ", label: "Azerbaijan", labelAr: "أذربيجان" },
  { value: "BS", label: "Bahamas", labelAr: "باهاماس" },
  { value: "BH", label: "Bahrain", labelAr: "البحرين" },
  { value: "BD", label: "Bangladesh", labelAr: "بنغلاديش" },
  { value: "BB", label: "Barbados", labelAr: "بربادوس" },
  { value: "BY", label: "Belarus", labelAr: "بيلاروسيا" },
  { value: "BE", label: "Belgium", labelAr: "بلجيكا" },
  { value: "BZ", label: "Belize", labelAr: "بليز" },
  { value: "BJ", label: "Benin", labelAr: "بنين" },
  { value: "BT", label: "Bhutan", labelAr: "بوتان" },
  { value: "BO", label: "Bolivia", labelAr: "بوليفيا" },
  { value: "BA", label: "Bosnia and Herzegovina", labelAr: "البوسنة والهرسك" },
  { value: "BW", label: "Botswana", labelAr: "بوتسوانا" },
  { value: "BR", label: "Brazil", labelAr: "البرازيل" },
  { value: "BN", label: "Brunei", labelAr: "بروناي" },
  { value: "BG", label: "Bulgaria", labelAr: "بلغاريا" },
  { value: "BF", label: "Burkina Faso", labelAr: "بوركينا فاسو" },
  { value: "BI", label: "Burundi", labelAr: "بوروندي" },
  { value: "CV", label: "Cabo Verde", labelAr: "الرأس الأخضر" },
  { value: "KH", label: "Cambodia", labelAr: "كمبوديا" },
  { value: "CM", label: "Cameroon", labelAr: "الكاميرون" },
  { value: "CA", label: "Canada", labelAr: "كندا" },
  { value: "CF", label: "Central African Republic", labelAr: "جمهورية أفريقيا الوسطى" },
  { value: "TD", label: "Chad", labelAr: "تشاد" },
  { value: "CL", label: "Chile", labelAr: "تشيلي" },
  { value: "CN", label: "China", labelAr: "الصين" },
  { value: "CO", label: "Colombia", labelAr: "كولومبيا" },
  { value: "KM", label: "Comoros", labelAr: "جزر القمر" },
  { value: "CG", label: "Congo", labelAr: "الكونغو" },
  { value: "CD", label: "Congo (DRC)", labelAr: "الكونغو الديمقراطية" },
  { value: "CR", label: "Costa Rica", labelAr: "كوستاريكا" },
  { value: "HR", label: "Croatia", labelAr: "كرواتيا" },
  { value: "CU", label: "Cuba", labelAr: "كوبا" },
  { value: "CY", label: "Cyprus", labelAr: "قبرص" },
  { value: "CZ", label: "Czech Republic", labelAr: "جمهورية التشيك" },
  { value: "DK", label: "Denmark", labelAr: "الدنمارك" },
  { value: "DJ", label: "Djibouti", labelAr: "جيبوتي" },
  { value: "DM", label: "Dominica", labelAr: "دومينيكا" },
  { value: "DO", label: "Dominican Republic", labelAr: "جمهورية الدومينيكان" },
  { value: "EC", label: "Ecuador", labelAr: "الإكوادور" },
  { value: "EG", label: "Egypt", labelAr: "مصر" },
  { value: "SV", label: "El Salvador", labelAr: "السلفادور" },
  { value: "GQ", label: "Equatorial Guinea", labelAr: "غينيا الاستوائية" },
  { value: "ER", label: "Eritrea", labelAr: "إريتريا" },
  { value: "EE", label: "Estonia", labelAr: "إستونيا" },
  { value: "SZ", label: "Eswatini", labelAr: "إسواتيني" },
  { value: "ET", label: "Ethiopia", labelAr: "إثيوبيا" },
  { value: "FJ", label: "Fiji", labelAr: "فيجي" },
  { value: "FI", label: "Finland", labelAr: "فنلندا" },
  { value: "FR", label: "France", labelAr: "فرنسا" },
  { value: "GA", label: "Gabon", labelAr: "الغابون" },
  { value: "GM", label: "Gambia", labelAr: "غامبيا" },
  { value: "GE", label: "Georgia", labelAr: "جورجيا" },
  { value: "DE", label: "Germany", labelAr: "ألمانيا" },
  { value: "GH", label: "Ghana", labelAr: "غانا" },
  { value: "GR", label: "Greece", labelAr: "اليونان" },
  { value: "GD", label: "Grenada", labelAr: "غرينادا" },
  { value: "GT", label: "Guatemala", labelAr: "غواتيمالا" },
  { value: "GN", label: "Guinea", labelAr: "غينيا" },
  { value: "GW", label: "Guinea-Bissau", labelAr: "غينيا بيساو" },
  { value: "GY", label: "Guyana", labelAr: "غيانا" },
  { value: "HT", label: "Haiti", labelAr: "هايتي" },
  { value: "HN", label: "Honduras", labelAr: "هندوراس" },
  { value: "HU", label: "Hungary", labelAr: "المجر" },
  { value: "IS", label: "Iceland", labelAr: "آيسلندا" },
  { value: "IN", label: "India", labelAr: "الهند" },
  { value: "ID", label: "Indonesia", labelAr: "إندونيسيا" },
  { value: "IR", label: "Iran", labelAr: "إيران" },
  { value: "IQ", label: "Iraq", labelAr: "العراق" },
  { value: "IE", label: "Ireland", labelAr: "أيرلندا" },
  { value: "IL", label: "Israel", labelAr: "إسرائيل" },
  { value: "IT", label: "Italy", labelAr: "إيطاليا" },
  { value: "JM", label: "Jamaica", labelAr: "جامايكا" },
  { value: "JP", label: "Japan", labelAr: "اليابان" },
  { value: "JO", label: "Jordan", labelAr: "الأردن" },
  { value: "KZ", label: "Kazakhstan", labelAr: "كازاخستان" },
  { value: "KE", label: "Kenya", labelAr: "كينيا" },
  { value: "KI", label: "Kiribati", labelAr: "كيريباتي" },
  { value: "KW", label: "Kuwait", labelAr: "الكويت" },
  { value: "KG", label: "Kyrgyzstan", labelAr: "قيرغيزستان" },
  { value: "LA", label: "Laos", labelAr: "لاوس" },
  { value: "LV", label: "Latvia", labelAr: "لاتفيا" },
  { value: "LB", label: "Lebanon", labelAr: "لبنان" },
  { value: "LS", label: "Lesotho", labelAr: "ليسوتو" },
  { value: "LR", label: "Liberia", labelAr: "ليبيريا" },
  { value: "LY", label: "Libya", labelAr: "ليبيا" },
  { value: "LI", label: "Liechtenstein", labelAr: "ليختنشتاين" },
  { value: "LT", label: "Lithuania", labelAr: "ليتوانيا" },
  { value: "LU", label: "Luxembourg", labelAr: "لوكسمبورغ" },
  { value: "MG", label: "Madagascar", labelAr: "مدغشقر" },
  { value: "MW", label: "Malawi", labelAr: "ملاوي" },
  { value: "MY", label: "Malaysia", labelAr: "ماليزيا" },
  { value: "MV", label: "Maldives", labelAr: "المالديف" },
  { value: "ML", label: "Mali", labelAr: "مالي" },
  { value: "MT", label: "Malta", labelAr: "مالطا" },
  { value: "MH", label: "Marshall Islands", labelAr: "جزر مارشال" },
  { value: "MR", label: "Mauritania", labelAr: "موريتانيا" },
  { value: "MU", label: "Mauritius", labelAr: "موريشيوس" },
  { value: "MX", label: "Mexico", labelAr: "المكسيك" },
  { value: "FM", label: "Micronesia", labelAr: "ميكرونيزيا" },
  { value: "MD", label: "Moldova", labelAr: "مولدوفا" },
  { value: "MC", label: "Monaco", labelAr: "موناكو" },
  { value: "MN", label: "Mongolia", labelAr: "منغوليا" },
  { value: "ME", label: "Montenegro", labelAr: "الجبل الأسود" },
  { value: "MA", label: "Morocco", labelAr: "المغرب" },
  { value: "MZ", label: "Mozambique", labelAr: "موزمبيق" },
  { value: "MM", label: "Myanmar", labelAr: "ميانمار" },
  { value: "NA", label: "Namibia", labelAr: "ناميبيا" },
  { value: "NR", label: "Nauru", labelAr: "ناورو" },
  { value: "NP", label: "Nepal", labelAr: "نيبال" },
  { value: "NL", label: "Netherlands", labelAr: "هولندا" },
  { value: "NZ", label: "New Zealand", labelAr: "نيوزيلندا" },
  { value: "NI", label: "Nicaragua", labelAr: "نيكاراغوا" },
  { value: "NE", label: "Niger", labelAr: "النيجر" },
  { value: "NG", label: "Nigeria", labelAr: "نيجيريا" },
  { value: "MK", label: "North Macedonia", labelAr: "مقدونيا الشمالية" },
  { value: "NO", label: "Norway", labelAr: "النرويج" },
  { value: "OM", label: "Oman", labelAr: "عُمان" },
  { value: "PK", label: "Pakistan", labelAr: "باكستان" },
  { value: "PW", label: "Palau", labelAr: "بالاو" },
  { value: "PS", label: "Palestine", labelAr: "فلسطين" },
  { value: "PA", label: "Panama", labelAr: "بنما" },
  { value: "PG", label: "Papua New Guinea", labelAr: "بابوا غينيا الجديدة" },
  { value: "PY", label: "Paraguay", labelAr: "باراغواي" },
  { value: "PE", label: "Peru", labelAr: "بيرو" },
  { value: "PH", label: "Philippines", labelAr: "الفلبين" },
  { value: "PL", label: "Poland", labelAr: "بولندا" },
  { value: "PT", label: "Portugal", labelAr: "البرتغال" },
  { value: "QA", label: "Qatar", labelAr: "قطر" },
  { value: "RO", label: "Romania", labelAr: "رومانيا" },
  { value: "RU", label: "Russia", labelAr: "روسيا" },
  { value: "RW", label: "Rwanda", labelAr: "رواندا" },
  { value: "KN", label: "Saint Kitts and Nevis", labelAr: "سانت كيتس ونيفيس" },
  { value: "LC", label: "Saint Lucia", labelAr: "سانت لوسيا" },
  { value: "VC", label: "Saint Vincent and the Grenadines", labelAr: "سانت فينسنت وجزر غرينادين" },
  { value: "WS", label: "Samoa", labelAr: "ساموا" },
  { value: "SM", label: "San Marino", labelAr: "سان مارينو" },
  { value: "ST", label: "Sao Tome and Principe", labelAr: "ساو تومي وبرينسيبي" },
  { value: "SA", label: "Saudi Arabia", labelAr: "المملكة العربية السعودية" },
  { value: "SN", label: "Senegal", labelAr: "السنغال" },
  { value: "RS", label: "Serbia", labelAr: "صربيا" },
  { value: "SC", label: "Seychelles", labelAr: "سيشل" },
  { value: "SL", label: "Sierra Leone", labelAr: "سيراليون" },
  { value: "SG", label: "Singapore", labelAr: "سنغافورة" },
  { value: "SK", label: "Slovakia", labelAr: "سلوفاكيا" },
  { value: "SI", label: "Slovenia", labelAr: "سلوفينيا" },
  { value: "SB", label: "Solomon Islands", labelAr: "جزر سليمان" },
  { value: "SO", label: "Somalia", labelAr: "الصومال" },
  { value: "ZA", label: "South Africa", labelAr: "جنوب أفريقيا" },
  { value: "SS", label: "South Sudan", labelAr: "جنوب السودان" },
  { value: "ES", label: "Spain", labelAr: "إسبانيا" },
  { value: "LK", label: "Sri Lanka", labelAr: "سريلانكا" },
  { value: "SD", label: "Sudan", labelAr: "السودان" },
  { value: "SR", label: "Suriname", labelAr: "سورينام" },
  { value: "SE", label: "Sweden", labelAr: "السويد" },
  { value: "CH", label: "Switzerland", labelAr: "سويسرا" },
  { value: "SY", label: "Syria", labelAr: "سوريا" },
  { value: "TW", label: "Taiwan", labelAr: "تايوان" },
  { value: "TJ", label: "Tajikistan", labelAr: "طاجيكستان" },
  { value: "TZ", label: "Tanzania", labelAr: "تنزانيا" },
  { value: "TH", label: "Thailand", labelAr: "تايلاند" },
  { value: "TL", label: "Timor-Leste", labelAr: "تيمور الشرقية" },
  { value: "TG", label: "Togo", labelAr: "توغو" },
  { value: "TO", label: "Tonga", labelAr: "تونغا" },
  { value: "TT", label: "Trinidad and Tobago", labelAr: "ترينيداد وتوباغو" },
  { value: "TN", label: "Tunisia", labelAr: "تونس" },
  { value: "TR", label: "Turkey", labelAr: "تركيا" },
  { value: "TM", label: "Turkmenistan", labelAr: "تركمانستان" },
  { value: "TV", label: "Tuvalu", labelAr: "توفالو" },
  { value: "UG", label: "Uganda", labelAr: "أوغندا" },
  { value: "UA", label: "Ukraine", labelAr: "أوكرانيا" },
  { value: "AE", label: "United Arab Emirates", labelAr: "الإمارات العربية المتحدة" },
  { value: "GB", label: "United Kingdom", labelAr: "المملكة المتحدة" },
  { value: "US", label: "United States", labelAr: "الولايات المتحدة" },
  { value: "UY", label: "Uruguay", labelAr: "أوروغواي" },
  { value: "UZ", label: "Uzbekistan", labelAr: "أوزبكستان" },
  { value: "VU", label: "Vanuatu", labelAr: "فانواتو" },
  { value: "VE", label: "Venezuela", labelAr: "فنزويلا" },
  { value: "VN", label: "Vietnam", labelAr: "فيتنام" },
  { value: "YE", label: "Yemen", labelAr: "اليمن" },
  { value: "ZM", label: "Zambia", labelAr: "زامبيا" },
  { value: "ZW", label: "Zimbabwe", labelAr: "زيمبابوي" },
  { value: "OTHER", label: "Other", labelAr: "أخرى" },
];

export function getCountryLabel(value: string, lang?: string): string {
  const country = COUNTRIES.find(c => c.value === value);
  if (!country) return value;
  if (lang === "ar" && country.labelAr) return country.labelAr;
  return country.label;
}
